"""
src/detection/train_yolo.py

Train a YOLOv8 object detection model (Bird vs Drone) using the ultralytics package.

Requirements:
    pip install ultralytics

Assumptions:
    - YOLO dataset is prepared under:
        data/object_detection_Dataset/...

    - configs/yolov8_data.yaml exists (generated by src.detection.prepare_yolo)
      Example YAML:
        path: data/object_detection_Dataset
        train: train
        val: val
        test: test
        names:
          0: bird
          1: drone

    - This script will:
        * Load a YOLOv8 model (e.g. yolov8n.pt)
        * Train on the dataset
        * Save best weights to: models/detection/yolov8{size}_best.pt
        * Let ultralytics handle its own runs directory (by default runs/detect or runs/train)

Usage (from project root):

    # Basic training with small model (n), 50 epochs, img size 640:
    python -m src.detection.train_yolo

    # Specify size, epochs, and image size:
    python -m src.detection.train_yolo --model-size n --epochs 50 --img-size 640 640

    # Use 's' (small) model:
    python -m src.detection.train_yolo --model-size s
"""

from __future__ import annotations

import argparse
import shutil
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Tuple, Optional

# We import ultralytics inside a try/except so we can give a nice message if missing.
try:
    from ultralytics import YOLO
except ImportError:
    YOLO = None  # type: ignore


# ---------------------------------------------------------------------
# Config dataclass
# ---------------------------------------------------------------------
@dataclass
class YoloTrainConfig:
    project_root: Path
    data_yaml: Path
    models_dir: Path
    runs_dir: Path

    model_size: str = "n"           # "n", "s", "m", "l", "x"
    pretrained_weights: Optional[str] = None  # e.g. "yolov8n.pt" or custom .pt
    epochs: int = 10
    img_size: Tuple[int, int] = (200, 200)  # (height, width)
    batch_size: int = 8
    device: str = "cpu"             # "cpu" or "0" (GPU id) if CUDA is available
    workers: int = 2                # dataloader workers
    save_best_name: Optional[str] = None  # computed from model_size


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------
def get_project_root(start: Optional[Path] = None) -> Path:
    if start is None:
        start = Path().resolve()
    if start.name == "notebooks":
        return start.parent
    return start


def build_pretrained_name(model_size: str) -> str:
    """
    Map a YOLO size letter to a default pretrained model name.
    """
    model_size = model_size.lower()
    return f"yolov8{model_size}.pt"  # e.g. yolov8n.pt, yolov8s.pt


def build_save_best_name(model_size: str) -> str:
    """
    Name for saving best weights in models/detection.
    """
    model_size = model_size.lower()
    return f"yolov8{model_size}_best.pt"


# ---------------------------------------------------------------------
# Training logic
# ---------------------------------------------------------------------
def train_yolov8(cfg: YoloTrainConfig) -> None:
    if YOLO is None:
        print("❌ The 'ultralytics' package is not installed.")
        print("   Install it with: pip install ultralytics")
        return

    if not cfg.data_yaml.exists():
        print(f"❌ YOLO data.yaml not found at: {cfg.data_yaml}")
        print("   Run: python -m src.detection.prepare_yolo")
        return

    # Decide which pretrained weights to use
    if cfg.pretrained_weights is None:
        pretrained = build_pretrained_name(cfg.model_size)
    else:
        pretrained = cfg.pretrained_weights

    print("\n📌 YOLOv8 training configuration:")
    print(asdict(cfg))
    print("\nUsing pretrained weights:", pretrained)
    print("Using data config       :", cfg.data_yaml)

    # Create directories
    cfg.models_dir.mkdir(parents=True, exist_ok=True)
    cfg.runs_dir.mkdir(parents=True, exist_ok=True)

    # Initialize YOLO model
    print("\n🔧 Initializing YOLO model...")
    model = YOLO(pretrained)  # this will download weights if not present

    # Train
    print("\n🚀 Starting YOLOv8 training...\n")
    # We let ultralytics handle its own "runs" project name,
    # but we set project to our project_root/runs/yolo for organization.
    train_results = model.train(
        data=str(cfg.data_yaml),
        epochs=cfg.epochs,
        imgsz=list(cfg.img_size),
        batch=cfg.batch_size,
        device=cfg.device,
        workers=cfg.workers,
        project=str(cfg.runs_dir),
        name=f"yolov8{cfg.model_size}_det",
        exist_ok=True,
        verbose=True,
    )

    # train_results.save_dir is where ultralytics stored this run
    run_dir = Path(train_results.save_dir)
    weights_dir = run_dir / "weights"
    best_pt = weights_dir / "best.pt"

    print("\n🏁 Training completed.")
    print("Run directory:", run_dir)

    if not best_pt.exists():
        print("⚠️ best.pt not found in:", weights_dir)
        print("   Check YOLO logs for details.")
        return

    # Copy best.pt to models/detection/yolov8{size}_best.pt
    dst_best = cfg.models_dir / (cfg.save_best_name or build_save_best_name(cfg.model_size))

    shutil.copy2(best_pt, dst_best)
    print(f"\n✅ Best weights copied to: {dst_best}")
    print("You can now use this .pt file for inference in infer_yolo.py or in notebooks.")


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a YOLOv8 object detection model for Bird vs Drone."
    )
    parser.add_argument(
        "--root",
        type=str,
        default=None,
        help="Project root path. If not provided, auto-detect from current directory.",
    )
    parser.add_argument(
        "--data-yaml",
        type=str,
        default="configs/yolov8_data.yaml",
        help="Relative path to YOLOv8 data.yaml (default: configs/yolov8_data.yaml).",
    )
    parser.add_argument(
        "--model-size",
        type=str,
        default="n",
        choices=["n", "s", "m", "l", "x"],
        help="YOLOv8 model size: n, s, m, l, x (default: n).",
    )
    parser.add_argument(
        "--pretrained-weights",
        type=str,
        default=None,
        help="Pretrained weights .pt file. If not set, will use yolov8{size}.pt.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=10,
        help="Number of training epochs (default: 10).",
    )
    parser.add_argument(
        "--img-size",
        type=int,
        nargs=2,
        default=[200,200],
        help="Image size as: --img-size H W (default: 200 200).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=8,
        help="Batch size (default: 8).",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Device for training: 'cpu' or '0' for first GPU, etc. (default: cpu).",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=2,
        help="Number of dataloader workers (default: 2).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    project_root = Path(args.root).resolve() if args.root else get_project_root()
    data_yaml = project_root / args.data_yaml
    models_dir = project_root / "models" / "detection"
    runs_dir = project_root / "runs" / "yolo"

    cfg = YoloTrainConfig(
        project_root=project_root,
        data_yaml=data_yaml,
        models_dir=models_dir,
        runs_dir=runs_dir,
        model_size=args.model_size,
        pretrained_weights=args.pretrained_weights,
        epochs=args.epochs,
        img_size=(args.img_size[0], args.img_size[1]),
        batch_size=args.batch_size,
        device=args.device,
        workers=args.workers,
    )
    cfg.save_best_name = build_save_best_name(cfg.model_size)

    train_yolov8(cfg)


if __name__ == "__main__":
    main()
